package br.com.ifba.academia.fichatreino.view;

import br.com.ifba.academia.exercicio.controller.ExercicioIController;
import br.com.ifba.academia.exercicio.entity.Exercicio;
import br.com.ifba.academia.fichatreino.controller.FichaTreinoIController;
import br.com.ifba.academia.fichatreino.entity.FichaTreino;
import br.com.ifba.academia.fichatreino.entity.ItemFicha;
import br.com.ifba.academia.pessoa.controller.PessoaIController;
import br.com.ifba.academia.pessoa.entity.Pessoa;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class CadastrarTreino extends javax.swing.JFrame {

    private FichaTreinoIController fichaTreinoService;
    private ExercicioIController exercicioService;
    private PessoaIController pessoaService;
    
    private FichaTreino fichaEdicao;
    private DefaultTableModel modeloBanco;
    private DefaultTableModel modeloTreino;
    private TableRowSorter<DefaultTableModel> sorterBanco;
    private List<Pessoa> alunosCadastrados;

    public CadastrarTreino(FichaTreinoIController fichaTreinoService, ExercicioIController exercicioService, PessoaIController pessoaService) {
        this.fichaTreinoService = fichaTreinoService;
        this.exercicioService = exercicioService;
        this.pessoaService = pessoaService;
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        inicializarTabelas();
        carregarComboboxAlunos();
        carregarBancoExercicios();
        configurarFiltroExercicios();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarTreino.class.getName());

    /**
     * Creates new form GerenciarAluno
     */
    public CadastrarTreino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBancoExercicios = new javax.swing.JTable();
        txtPesquisarExercicio = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        cbxAlunos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTreinoMontado = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        lblMontandoTreino = new javax.swing.JLabel();
        lblExerciciosDisponiveis = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(16, 30, 79));

        tblBancoExercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBancoExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBancoExerciciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBancoExercicios);

        txtPesquisarExercicio.addActionListener(this::txtPesquisarExercicioActionPerformed);

        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquisar:");

        jLabel1.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciar Treino");

        txtDescricao.addActionListener(this::txtDescricaoActionPerformed);

        cbxAlunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblTreinoMontado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTreinoMontado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreinoMontadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTreinoMontado);

        btnSalvar.setBackground(new java.awt.Color(51, 153, 0));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        lblMontandoTreino.setForeground(new java.awt.Color(255, 255, 255));
        lblMontandoTreino.setText("Montando Treino:");

        lblExerciciosDisponiveis.setForeground(new java.awt.Color(255, 255, 255));
        lblExerciciosDisponiveis.setText("Exercicios Disponiveis:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aluno:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblExerciciosDisponiveis)
                        .addGap(97, 866, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisarExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMontandoTreino)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbxAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(390, 390, 390))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(lblExerciciosDisponiveis)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisar)
                    .addComponent(lblMontandoTreino)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBancoExerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBancoExerciciosMouseClicked
        
        int linha = tblBancoExercicios.getSelectedRow();
        int coluna = tblBancoExercicios.columnAtPoint(evt.getPoint());
        if (linha == -1) return;
        
        int linhaModel = tblBancoExercicios.convertRowIndexToModel(linha);

        if (coluna == 3) {
            Object idEx = modeloBanco.getValueAt(linhaModel, 0);
            Object nomeEx = modeloBanco.getValueAt(linhaModel, 1);
            modeloTreino.addRow(new Object[]{idEx, nomeEx, 0, 0, 0.0, "❌ REMOVER"});
        }
    }//GEN-LAST:event_tblBancoExerciciosMouseClicked

    private void txtPesquisarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarExercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarExercicioActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
       if (cbxAlunos.getSelectedIndex() == 0 || txtDescricao.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha a descrição e selecione um aluno!");
            return;
        }

        try {
            FichaTreino ficha = (this.fichaEdicao != null) ? this.fichaEdicao : new FichaTreino();
            ficha.setDescricao(txtDescricao.getText());
            
            if (ficha.getId() == null) {
                ficha.setDataCriacao(LocalDate.now());
                ficha.setAtivo(true);
            }
            
            Pessoa alunoSelecionado = alunosCadastrados.get(cbxAlunos.getSelectedIndex() - 1);
            ficha.setAluno(alunoSelecionado);

            
            if (ficha.getItens() == null) {
                ficha.setItens(new ArrayList<>());
            } else {
                List<ItemFicha> itensAntigos = new ArrayList<>(ficha.getItens());
                for (ItemFicha itemAntigo : itensAntigos) {
                    ficha.removerItem(itemAntigo); 
                }
            }

            for (int i = 0; i < modeloTreino.getRowCount(); i++) {
                Long exId = Long.parseLong(modeloTreino.getValueAt(i, 0).toString());
                Exercicio ex = exercicioService.findById(exId);
                
                ItemFicha item = new ItemFicha();
                item.setExercicio(ex);
                item.setSeries(Integer.parseInt(modeloTreino.getValueAt(i, 2).toString()));
                item.setRepeticoes(Integer.parseInt(modeloTreino.getValueAt(i, 3).toString()));
                item.setCarga(Double.parseDouble(modeloTreino.getValueAt(i, 4).toString()));
                
                ficha.adicionarItem(item);
            }

            
            if (ficha.getId() == null) {
                fichaTreinoService.save(ficha);
                JOptionPane.showMessageDialog(this, "Treino cadastrado com sucesso!");
            } else {
                fichaTreinoService.update(ficha);
                JOptionPane.showMessageDialog(this, "Treino atualizado com sucesso!");
            }

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar treino: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblTreinoMontadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTreinoMontadoMouseClicked
        
        int linha = tblTreinoMontado.getSelectedRow();
        int coluna = tblTreinoMontado.columnAtPoint(evt.getPoint());
        if (linha == -1) return;

        if (coluna >= 2 && coluna <= 4) {
            String titulo = tblTreinoMontado.getColumnName(coluna);
            String valorAtual = tblTreinoMontado.getValueAt(linha, coluna).toString();
            String novoValor = JOptionPane.showInputDialog(this, "Definir " + titulo + ":", valorAtual);
            
            if (novoValor != null && !novoValor.trim().isEmpty()) {
                try {
                    if (coluna == 4) Double.parseDouble(novoValor); else Integer.parseInt(novoValor);
                    tblTreinoMontado.setValueAt(novoValor, linha, coluna);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Por favor, digite um número válido.");
                }
            }
        } else if (coluna == 5) {
            modeloTreino.removeRow(linha);
        }
        
    }//GEN-LAST:event_tblTreinoMontadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarTreino().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxAlunos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExerciciosDisponiveis;
    private javax.swing.JLabel lblMontandoTreino;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tblBancoExercicios;
    private javax.swing.JTable tblTreinoMontado;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisarExercicio;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabelas() {
        //tabela de exerc.
        modeloBanco = new DefaultTableModel(new Object[][]{}, new String[]{"ID", "Nome", "Músculo", "Ação"}) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblBancoExercicios.setModel(modeloBanco);
        sorterBanco = new TableRowSorter<>(modeloBanco);
        tblBancoExercicios.setRowSorter(sorterBanco);

        //tabela do treino sendo montado 
        modeloTreino = new DefaultTableModel(new Object[][]{}, new String[]{"ID Exercicio", "Exercício", "Séries", "Repetições", "Carga(kg)", "Ação"}) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblTreinoMontado.setModel(modeloTreino);
    }
    
    private void carregarComboboxAlunos() {
        cbxAlunos.removeAllItems();
        cbxAlunos.addItem("Selecione um Aluno");
        
        alunosCadastrados = new ArrayList<>();
        List<Pessoa> todasPessoas = pessoaService.findAll();
        
        if (todasPessoas == null) {
            return;
        }
        
        for (Pessoa p : todasPessoas) {
            if (p == null) {
                continue;
            }
            
            boolean isAdmin = p.getIsAdministrador() != null && p.getIsAdministrador();
            boolean isAdminPadrao = p.getCpf() != null && p.getCpf().equals("00000000000");
            boolean isNomeAdmin = p.getNome() != null && p.getNome().equalsIgnoreCase("Administrador Padrão");
            boolean isAtivo = p.getAtivo() != null && p.getAtivo();
            
            if (isAdmin || isAdminPadrao || isNomeAdmin || !isAtivo) {
                continue;
            }
            
            alunosCadastrados.add(p);
            cbxAlunos.addItem(p.getNome() + " - " + p.getCpf());
        }
    }

    private void carregarBancoExercicios() {
        modeloBanco.setRowCount(0);
        List<Exercicio> exercicios = exercicioService.findAll();
        for (Exercicio ex : exercicios) {
            if (ex.getAtivo()) {
                modeloBanco.addRow(new Object[]{ex.getId(), ex.getNome(), ex.getGrupoMuscular(), "➕ ADICIONAR"});
            }
        }
    }
    
    public void preencherCamposParaEdicao(FichaTreino ficha) {
        this.fichaEdicao = ficha;
        txtDescricao.setText(ficha.getDescricao());
        btnSalvar.setText("Salvar Alterações");
        
        for (int i = 0; i < alunosCadastrados.size(); i++) {
            if (alunosCadastrados.get(i).getId().equals(ficha.getAluno().getId())) {
                cbxAlunos.setSelectedIndex(i + 1);
                break;
            }
        }
        
        modeloTreino.setRowCount(0);
        for (ItemFicha item : ficha.getItens()) {
            modeloTreino.addRow(new Object[]{
                item.getExercicio().getId(),
                item.getExercicio().getNome(),
                item.getSeries(),
                item.getRepeticoes(),
                item.getCarga(),
                "❌ Remover"
            });
        }
    }
    
    private void configurarFiltroExercicios() {
        txtPesquisarExercicio.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { sorterBanco.setRowFilter(RowFilter.regexFilter("(?i)" + txtPesquisarExercicio.getText(), 1)); }
            @Override
            public void removeUpdate(DocumentEvent e) { sorterBanco.setRowFilter(RowFilter.regexFilter("(?i)" + txtPesquisarExercicio.getText(), 1)); }
            @Override
            public void changedUpdate(DocumentEvent e) { sorterBanco.setRowFilter(RowFilter.regexFilter("(?i)" + txtPesquisarExercicio.getText(), 1)); }
        });
    }
}