package br.com.ifba.academia.exercicio.view;

import br.com.ifba.academia.exercicio.controller.ExercicioIController;
import br.com.ifba.academia.exercicio.entity.Exercicio;
import br.com.ifba.academia.fichatreino.controller.FichaTreinoIController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class GerenciarExercicio extends javax.swing.JFrame {
    
    private ExercicioIController exercicioService;
    private FichaTreinoIController fichaTreinoService;
    private DefaultTableModel modeloTabela;
    private TableRowSorter<DefaultTableModel> sorter;
    
   public GerenciarExercicio(ExercicioIController exercicioService, FichaTreinoIController fichaTreinoService) {
        this.exercicioService = exercicioService;
        this.fichaTreinoService = fichaTreinoService;
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabela();
        preencherTabela();
        configurarFiltroDinamico();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarExercicio.class.getName());

    /**
     * Creates new form GerenciarAluno
     */
    public GerenciarExercicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExercicios = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(16, 30, 79));

        tblExercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExerciciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExercicios);

        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquisar");

        lblTitulo.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("EXERCICIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPesquisar)
                        .addGap(406, 406, 406)
                        .addComponent(lblTitulo))
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(438, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblExerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExerciciosMouseClicked
        
        int linhaView = tblExercicios.getSelectedRow();
        if (linhaView == -1) return;

        int linhaModel = tblExercicios.convertRowIndexToModel(linhaView);
        int coluna = tblExercicios.columnAtPoint(evt.getPoint());
        Long id = (Long) modeloTabela.getValueAt(linhaModel, 0);

        if (coluna == 5) {
            try {
                Exercicio exercicio = exercicioService.findById(id);
                CadastroExercicio telaCadastro = new CadastroExercicio(exercicioService, fichaTreinoService);
                telaCadastro.preencherCamposParaEdicao(exercicio);
                telaCadastro.setVisible(true);
                
                telaCadastro.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                        preencherTabela();
                    }
                });
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Exercício não encontrado.");
            }
        } else if (coluna == 6) {
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir este exercício?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    exercicioService.delete(id);
                    JOptionPane.showMessageDialog(this, "Exercício excluído!");
                    preencherTabela();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
                }
            }
        }
        
    }//GEN-LAST:event_tblExerciciosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GerenciarExercicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblExercicios;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabela() {
        modeloTabela = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Nome", "Séries", "Repetições", "Carga (kg)", "Editar", "Excluir"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblExercicios.setModel(modeloTabela);
        sorter = new TableRowSorter<>(modeloTabela);
        tblExercicios.setRowSorter(sorter);
    }

    public void preencherTabela() {
        modeloTabela.setRowCount(0);
        try {
            List<Exercicio> lista = exercicioService.findAll();
            for (Exercicio e : lista) {
                modeloTabela.addRow(new Object[]{
                    e.getId(), e.getNome(), e.getSeries(), e.getRepeticoes(), e.getCarga(),
                    "✏️ Editar", "❌ Excluir"
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

    private void configurarFiltroDinamico() {
        txtPesquisa.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }

            private void filtrar() {
                String texto = txtPesquisa.getText();
                if (texto.trim().length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    // Filtra ignorando maiúsculas/minúsculas
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
                }
            }
        });
    }
    
}


