package br.com.ifba.academia.planoaluno.view;

import br.com.ifba.academia.pessoa.controller.PessoaIController;
import br.com.ifba.academia.pessoa.entity.Pessoa;
import br.com.ifba.academia.plano.controller.PlanoIController;
import br.com.ifba.academia.plano.entity.Plano;
import br.com.ifba.academia.planoaluno.entity.PlanoAluno;
import br.com.ifba.academia.planoaluno.controller.PlanoAlunoIController;
import java.util.List;
import javax.swing.JOptionPane;

public class CadastroPlanoAluno extends javax.swing.JFrame {
    
    private PlanoAlunoIController planoAlunoService;
    private PessoaIController pessoaService;
    private PlanoIController planoService;

    public CadastroPlanoAluno(PlanoAlunoIController planoAlunoService, PessoaIController pessoaService, PlanoIController planoService) {
        this.planoAlunoService = planoAlunoService;
        this.pessoaService = pessoaService;
        this.planoService = planoService;
        
        initComponents();
        
        cbAlunos.setRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                
                if (value instanceof br.com.ifba.academia.pessoa.entity.Pessoa) {
                    br.com.ifba.academia.pessoa.entity.Pessoa aluno = (br.com.ifba.academia.pessoa.entity.Pessoa) value;
                    setText(aluno.getNome() + " - " + aluno.getCpf());
                }
                return this;
            }
        });
        
        carregarComboBoxes(); 
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroPlanoAluno.class.getName());


    /**
     * Creates new form CadastroAluno
     */
    public CadastroPlanoAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblMatricular = new javax.swing.JLabel();
        cbAlunos = new javax.swing.JComboBox<>();
        cbPlanos = new javax.swing.JComboBox<>();
        lblSelecionePlano = new javax.swing.JLabel();
        lblSelecioneAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(16, 30, 79));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblTitulo.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("MATRICULAR ALUNO");

        btnSalvar.setBackground(new java.awt.Color(0, 102, 102));
        btnSalvar.setFont(new java.awt.Font("Inter Black", 0, 13)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 27, 129));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 51, 102));

        lblMatricular.setFont(new java.awt.Font("Inter Black", 0, 13)); // NOI18N
        lblMatricular.setForeground(new java.awt.Color(255, 255, 255));
        lblMatricular.setText("MATRICULAR");

        cbAlunos.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbAlunos.addActionListener(this::cbAlunosActionPerformed);

        cbPlanos.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbPlanos.addActionListener(this::cbPlanosActionPerformed);

        lblSelecionePlano.setForeground(new java.awt.Color(255, 255, 255));
        lblSelecionePlano.setText("Selecione o Plano:");

        lblSelecioneAluno.setForeground(new java.awt.Color(255, 255, 255));
        lblSelecioneAluno.setText("Selecione o Aluno:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbAlunos, 0, 247, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cbPlanos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblMatricular))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSelecionePlano))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSelecioneAluno)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMatricular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblSelecioneAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblSelecionePlano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPlanos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(615, 615, 615)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        
        try {
        Pessoa alunoSelecionado = (Pessoa) cbAlunos.getSelectedItem();
        Plano planoSelecionado = (Plano) cbPlanos.getSelectedItem();

        if (alunoSelecionado == null || planoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um aluno e um plano.");
            return;
        }

        PlanoAluno novaMatricula = new PlanoAluno();
        novaMatricula.setAluno(alunoSelecionado);
        novaMatricula.setPlano(planoSelecionado);
        //service seta dataInicio, dataVencimento e o Ativo

        planoAlunoService.save(novaMatricula);
        
        JOptionPane.showMessageDialog(this, "Aluno matriculado com sucesso!");
        this.dispose();

    } catch (Exception e) {
        // Vai capturar o throw new RuntimeException("Este aluno ja possui um plano ativo...") do seu service
        JOptionPane.showMessageDialog(this, "Erro ao matricular: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlunosActionPerformed

    private void cbPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroPlanoAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Pessoa> cbAlunos;
    private javax.swing.JComboBox<Plano> cbPlanos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMatricular;
    private javax.swing.JLabel lblSelecioneAluno;
    private javax.swing.JLabel lblSelecionePlano;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    
    private void carregarComboBoxes() {
        cbAlunos.removeAllItems();
        cbPlanos.removeAllItems();

        try {
            List<Pessoa> pessoas = pessoaService.findAll();
            for (Pessoa p : pessoas) {
                
                boolean isFlagAdmin = (p.getIsAdministrador() != null && p.getIsAdministrador());
                boolean isAdminPadrao = (p.getCpf() != null && p.getCpf().equals("00000000000"));
                boolean isNomeAdmin = (p.getNome() != null && p.getNome().equalsIgnoreCase("Administrador Padrão"));
                
                if (isFlagAdmin || isAdminPadrao || isNomeAdmin) {
                    continue; 
                }
                
                cbAlunos.addItem(p);
            }

            List<Plano> planos = planoService.findAll();
            for (Plano plano : planos) {
                cbPlanos.addItem(plano);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
        }
    }
}