/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifba.academia.view;

import com.ifba.academia.model.Usuario;
import com.ifba.academia.model.PlanoAluno;
import com.ifba.academia.model.FichaTreino;
import com.ifba.academia.model.Exercicio;
import com.ifba.academia.service.PlanoAlunoService;
import com.ifba.academia.service.FichaTreinoService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evandro
 */
public class DashboardAluno extends javax.swing.JFrame {
    
    private Usuario alunoLogado;
    private PlanoAlunoService planoAlunoService;
    private FichaTreinoService fichaTreinoService;

    public DashboardAluno(Usuario alunoLogado, PlanoAlunoService planoAlunoService, FichaTreinoService fichaTreinoService) {
        this.alunoLogado = alunoLogado;
        this.planoAlunoService = planoAlunoService;
        this.fichaTreinoService = fichaTreinoService;
        
        initComponents(); 
        carregarDadosDoAluno();
    }
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAluno.class.getName());

    /**
     * Creates new form DashboardAluno
     */
    public DashboardAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBemVindo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlanoStatus = new javax.swing.JLabel();
        lblVencimento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFichaTreino = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblBemVindo.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        lblBemVindo.setText("BEM VINDO(A)");

        jLabel2.setFont(new java.awt.Font("Inter Black", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUAS INFORMAÇÕES");

        lblPlanoStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblPlanoStatus.setText("Status plano:");

        lblVencimento.setForeground(new java.awt.Color(255, 255, 255));
        lblVencimento.setText("Vencimento:");

        tblFichaTreino.setBackground(new java.awt.Color(51, 51, 51));
        tblFichaTreino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Exercício", "Séries", "Repetições", "Carga"
            }
        ));
        jScrollPane1.setViewportView(tblFichaTreino);

        jLabel9.setFont(new java.awt.Font("Inter Black", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TREINO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(lblBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPlanoStatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVencimento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(230, 230, 230))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBemVindo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPlanoStatus)
                        .addGap(18, 18, 18)
                        .addComponent(lblVencimento)
                        .addGap(354, 354, 354))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblPlanoStatus;
    private javax.swing.JLabel lblVencimento;
    private javax.swing.JTable tblFichaTreino;
    // End of variables declaration//GEN-END:variables

    private void carregarDadosDoAluno() {
        lblBemVindo.setText("Bem-vindo(a), " + alunoLogado.getNome());

        try {
            PlanoAluno planoAtual = planoAlunoService.buscarPlanoAtivo(alunoLogado.getId());
            
            if (planoAtual != null) {
                lblPlanoStatus.setText("Status do Plano: ATIVO");
                java.time.format.DateTimeFormatter formatador = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                lblVencimento.setText("Vencimento: " + planoAtual.getDataVencimento().format(formatador));
            } else {
                lblPlanoStatus.setText("Status do Plano: INATIVO / SEM PLANO");
                lblVencimento.setText("Vencimento: ---");
            }
        } catch (Exception e) {
            lblPlanoStatus.setText("Status do Plano: ERRO AO CARREGAR");
        }

        atualizarTabelaTreino();
    }

    private void atualizarTabelaTreino() {
        DefaultTableModel modelo = (DefaultTableModel) tblFichaTreino.getModel();
        modelo.setRowCount(0); 

        try {
            FichaTreino ficha = fichaTreinoService.buscarFichaAtual(alunoLogado.getId());
            
            if (ficha != null && ficha.getExercicios() != null) {
                for (Exercicio ex : ficha.getExercicios()) {
                    modelo.addRow(new Object[]{
                        ex.getNome(), 
                        ex.getSeries(), 
                        ex.getRepeticoes(), 
                        ex.getCarga() + " kg"
                    });
                }
            } else {
                modelo.addRow(new Object[]{"Nenhuma ficha encontrada", "-", "-", "-"});
            }
        } catch (Exception e) {
            System.out.println("Erro ao buscar treinos: " + e.getMessage());
        }
    }
    
}
