package br.com.ifba.academia.pagamento.view;

import br.com.ifba.academia.pessoa.controller.PessoaIController;
import br.com.ifba.academia.usuario.entity.Usuario;
import br.com.ifba.academia.usuario.controller.UsuarioIController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.time.format.DateTimeFormatter;

public class TelaGerenciarPagamento extends javax.swing.JFrame {
    
    private UsuarioIController usuarioService;
    private PessoaIController pessoaService;
    private DefaultTableModel modeloTabela;
    private TableRowSorter<DefaultTableModel> sorter;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private br.com.ifba.academia.pagamento.controller.PagamentoIController pagamentoService;
    private br.com.ifba.academia.plano.controller.PlanoIController planoService;
    private br.com.ifba.academia.planoaluno.controller.PlanoAlunoIController planoAlunoService;
    private br.com.ifba.academia.pessoa.entity.Pessoa alunoSelecionado = null;
    private br.com.ifba.academia.plano.entity.Plano planoSelecionado = null;
    
    public TelaGerenciarPagamento(UsuarioIController usuarioService, 
        PessoaIController pessoaService,
        br.com.ifba.academia.pagamento.controller.PagamentoIController pagamentoService,
        br.com.ifba.academia.plano.controller.PlanoIController planoService,
        br.com.ifba.academia.planoaluno.controller.PlanoAlunoIController planoAlunoService) {
        
        this.usuarioService = usuarioService;
        this.pessoaService = pessoaService;
        this.pagamentoService = pagamentoService;
        this.planoService = planoService;
        this.planoAlunoService = planoAlunoService;
        
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabela();
        preencherTabela();
        configurarFiltroDinamico();
        preencherComboFormasPagamento();
        
        cbxPlanos.setEnabled(false);
        cbxPlanos.removeAllItems();
        cbxPlanos.addItem("Selecione um aluno na tabela...");
        
        cbxFormaPagamento.addActionListener(evt -> atualizarResumo());
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaGerenciarPagamento.class.getName());

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        lblPagamento = new javax.swing.JLabel();
        cbxPlanos = new javax.swing.JComboBox<>();
        cbxFormaPagamento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblResumo = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(16, 30, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlunos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, 296, 240));
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 179, -1));

        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquise um aluno pelo nome:");
        jPanel1.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, -1, -1));

        lblPagamento.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        lblPagamento.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento.setText("PAGAMENTO");
        jPanel1.add(lblPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 11, -1, -1));

        cbxPlanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 89, 237, 50));

        cbxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 182, 237, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecione um Metodo de Pagamento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 160, -1, -1));

        lblResumo.setFont(new java.awt.Font("Inter Black", 0, 14)); // NOI18N
        lblResumo.setForeground(new java.awt.Color(255, 255, 255));
        lblResumo.setText("Nenhum aluno selecionado");
        jPanel1.add(lblResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 630, 30));

        btnConfirmar.setBackground(new java.awt.Color(51, 102, 0));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseClicked
        
        int linhaView = tblAlunos.getSelectedRow();
        if (linhaView == -1) return;

        int linhaModel = tblAlunos.convertRowIndexToModel(linhaView);
        Long id = (Long) modeloTabela.getValueAt(linhaModel, 0);

        try {
            Usuario usuario = usuarioService.findById(id);
            alunoSelecionado = usuario.getPessoa(); 
            planoSelecionado = null;

            List<br.com.ifba.academia.planoaluno.entity.PlanoAluno> matriculas = planoAlunoService.findAll();
            for (br.com.ifba.academia.planoaluno.entity.PlanoAluno matricula : matriculas) {
                if (matricula.getAluno().getId().equals(alunoSelecionado.getId())) {
                    planoSelecionado = matricula.getPlano();
                    break;
                }
            }

            if (planoSelecionado == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Atenção: Este aluno não possui uma matrícula ativa! Cadastre-o em um plano primeiro.", "Aluno Sem Matrícula", javax.swing.JOptionPane.WARNING_MESSAGE);
                tblAlunos.clearSelection();
                alunoSelecionado = null;
                cbxPlanos.removeAllItems();
                cbxPlanos.addItem("Selecione um aluno na tabela...");
            } else {
                cbxPlanos.removeAllItems();
                cbxPlanos.addItem(planoSelecionado.getNome() + " - R$ " + planoSelecionado.getValor());
                cbxPlanos.setSelectedIndex(0);
            }
            
            atualizarResumo();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar matrícula: " + e.getMessage());
        }
    }//GEN-LAST:event_tblAlunosMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        if (alunoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um aluno na tabela!");
            return;
        }
        if (planoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um plano válido!");
            return;
        }
        
        String formaPag = cbxFormaPagamento.getSelectedItem().toString();

        try {
            br.com.ifba.academia.pagamento.entity.Pagamento pagamento = new br.com.ifba.academia.pagamento.entity.Pagamento();
            pagamento.setAluno(alunoSelecionado);
            pagamento.setValor(planoSelecionado.getValor());
            pagamento.setFormaPagamento(formaPag);
            pagamento.setDataPagamento(java.time.LocalDate.now());
            
            pagamentoService.save(pagamento);
            JOptionPane.showMessageDialog(this, "Pagamento registrado com sucesso!");
            
            alunoSelecionado = null;
            planoSelecionado = null;
            cbxPlanos.removeAllItems();
            cbxPlanos.addItem("Selecione um aluno na tabela...");
            tblAlunos.clearSelection();
            atualizarResumo();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar pagamento: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<Object> cbxFormaPagamento;
    private javax.swing.JComboBox<Object> cbxPlanos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblResumo;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabela() {
        modeloTabela = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Nome", "CPF", "Telefone"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblAlunos.setModel(modeloTabela);
        sorter = new TableRowSorter<>(modeloTabela);
        tblAlunos.setRowSorter(sorter);
    }

    public void preencherTabela() {
        modeloTabela.setRowCount(0);
        try {
            List<Usuario> lista = usuarioService.findAll();
            for (Usuario u : lista) {
                if ("ALUNO".equals(u.getPerfil())) {
                    modeloTabela.addRow(new Object[]{
                        u.getId(), u.getPessoa().getNome(), u.getPessoa().getCpf(),
                        u.getPessoa().getTelefone()
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar alunos: " + e.getMessage());
        }
    }

    
   private void atualizarResumo() {
        if (lblResumo == null) return;
        
        if (alunoSelecionado != null && planoSelecionado != null) {
            lblResumo.setText(String.format("Aluno: %s | Plano: %s | Receber: R$ %.2f", 
                    alunoSelecionado.getNome(), 
                    planoSelecionado.getNome(), 
                    planoSelecionado.getValor()));
            lblResumo.setForeground(new java.awt.Color(0, 153, 0));
        } else {
            lblResumo.setText("Selecione um aluno matriculado para continuar.");
            lblResumo.setForeground(java.awt.Color.RED);
        }
    }
   
   private void configurarFiltroDinamico() {
        txtPesquisa.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrar();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrar();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrar();
            }

            private void filtrar() {
                String texto = txtPesquisa.getText();
                if (texto.trim().length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
                }
            }
        });
    }
   
   private void preencherComboFormasPagamento() {
        if (cbxFormaPagamento == null) return;
        
        cbxFormaPagamento.removeAllItems();
        cbxFormaPagamento.addItem("Dinheiro");
        cbxFormaPagamento.addItem("PIX");
        cbxFormaPagamento.addItem("Cartão de Crédito");
        cbxFormaPagamento.addItem("Cartão de Débito");
    }
   
}


