package br.com.ifba.academia.usuario.view;

import br.com.ifba.academia.pagamento.controller.PagamentoIController;
import br.com.ifba.academia.pagamento.entity.Pagamento;
import br.com.ifba.academia.pessoa.controller.PessoaIController;
import br.com.ifba.academia.planoaluno.controller.PlanoAlunoIController;
import br.com.ifba.academia.planoaluno.entity.PlanoAluno;
import br.com.ifba.academia.pessoa.entity.Pessoa;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class ControleAcesso extends javax.swing.JFrame {

    private PessoaIController pessoaService;
    private PlanoAlunoIController planoAlunoService;
    private PagamentoIController pagamentoService;
    private DefaultTableModel modeloTabela;
    private TableRowSorter<DefaultTableModel> sorter;

    public ControleAcesso(PessoaIController pessoaService, PlanoAlunoIController planoAlunoService, PagamentoIController pagamentoService) {
        this.pessoaService = pessoaService;
        this.planoAlunoService = planoAlunoService;
        this.pagamentoService = pagamentoService;
        initComponents();
        this.setLocationRelativeTo(null);
        
        inicializarTabela();
        preencherTabela();
        configurarFiltroDinamico();
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ControleAcesso.class.getName());

    /**
     * Creates new form GerenciarAluno
     */
    public ControleAcesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPessoas = new javax.swing.JTable();
        txtPesquisaNome = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisaId = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(16, 30, 79));

        tblPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPessoasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPessoas);

        txtPesquisaNome.addActionListener(this::txtPesquisaNomeActionPerformed);

        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquisar por NOME:");

        jLabel1.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROLE DE ACESSO");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisar por ID:");

        btnVerificar.setText("Verificar Acesso");
        btnVerificar.addActionListener(this::btnVerificarActionPerformed);

        lblStatus.setFont(new java.awt.Font("Inter Black", 0, 18)); // NOI18N
        lblStatus.setText("AGUARDANDO...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPesquisar)
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPesquisaId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPesquisar)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(323, 323, 323))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPessoasMouseClicked
        
    }//GEN-LAST:event_tblPessoasMouseClicked

    private void txtPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaNomeActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
       int linhaView = tblPessoas.getSelectedRow();
        
        if (linhaView == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma pessoa na tabela primeiro.");
            return;
        }

        int linhaModel = tblPessoas.convertRowIndexToModel(linhaView);
        
        Long idAluno = (Long) modeloTabela.getValueAt(linhaModel, 0);
        Boolean pessoaAtiva = (Boolean) modeloTabela.getValueAt(linhaModel, 3);

        if (!pessoaAtiva) {
            lblStatus.setText("BLOQUEADO (CONTA INATIVA)");
            lblStatus.setForeground(Color.RED);
            return;
        }

        boolean possuiMatriculaValida = false;
        
        try {
            List<PlanoAluno> todosPlanos = planoAlunoService.findAll();
            
            for (PlanoAluno plano : todosPlanos) {
                if (plano.getAluno().getId().equals(idAluno) && plano.getAtivo()) {
                    possuiMatriculaValida = true;
                    break;
                }
            }

            if (!possuiMatriculaValida) {
                lblStatus.setText("BLOQUEADO (SEM MATRÍCULA)");
                lblStatus.setForeground(Color.RED); 
                return; 
            }
            
            boolean pagamentoEmDia = false;
            List<Pagamento> todosPagamentos = pagamentoService.findAll();
            
            java.time.LocalDate trintaDiasAtras = java.time.LocalDate.now().minusDays(30);
            
            for (Pagamento pag : todosPagamentos) {
                if (pag.getAluno().getId().equals(idAluno) && pag.getAtivo()) {
                    if (!pag.getDataPagamento().isBefore(trintaDiasAtras)) {
                        pagamentoEmDia = true;
                        break;
                    }
                }
            }

            if (pagamentoEmDia) {
                lblStatus.setText("LIBERADO");
                lblStatus.setForeground(new java.awt.Color(0, 153, 0));
            } else {
                lblStatus.setText("BLOQUEADO (INADIMPLENTE)");
                lblStatus.setForeground(Color.RED);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao verificar acesso: " + e.getMessage());
            lblStatus.setText("ERRO DE CONEXÃO");
            lblStatus.setForeground(Color.ORANGE);
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ControleAcesso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblPessoas;
    private javax.swing.JTextField txtPesquisaId;
    private javax.swing.JTextField txtPesquisaNome;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabela() {
        modeloTabela = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Nome", "CPF", "Status Conta"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblPessoas.setModel(modeloTabela);
        
        sorter = new TableRowSorter<>(modeloTabela);
        tblPessoas.setRowSorter(sorter);
    }

    private void preencherTabela() {
        modeloTabela.setRowCount(0);
        try {
            List<Pessoa> lista = pessoaService.findAll();
            for (Pessoa p : lista) {
                
                boolean isFlagAdmin = (p.getIsAdministrador() != null && p.getIsAdministrador());
                boolean isAdminPadrao = (p.getCpf() != null && p.getCpf().equals("00000000000"));
                boolean isNomeAdmin = (p.getNome() != null && p.getNome().equalsIgnoreCase("Administrador Padrão"));
                
                if (isFlagAdmin || isAdminPadrao || isNomeAdmin) {
                    continue; 
                }
                
                modeloTabela.addRow(new Object[]{
                    p.getId(), 
                    p.getNome(), 
                    p.getCpf(),
                    p.getAtivo()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
        }
    }

    private void configurarFiltroDinamico() {
        DocumentListener ouvinteFiltro = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        };

        txtPesquisaId.getDocument().addDocumentListener(ouvinteFiltro);
        txtPesquisaNome.getDocument().addDocumentListener(ouvinteFiltro);
    }

    private void filtrar() {
        String textoId = txtPesquisaId.getText().trim();
        String textoNome = txtPesquisaNome.getText().trim();

        List<RowFilter<Object, Object>> filtros = new ArrayList<>();

        if (!textoId.isEmpty()) {
            filtros.add(RowFilter.regexFilter("^" + textoId + "$", 0));
        }
        
        if (!textoNome.isEmpty()) {
            filtros.add(RowFilter.regexFilter("(?i)" + textoNome, 1));
        }

        if (filtros.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.andFilter(filtros));
        }
    }
}


